# Generated by Django 2.1.3 on 2018-11-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20181117_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglistindi',
            name='total_available',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='bookinglistindi',
            name='total_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinglistorga',
            name='total_available',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='bookinglistorga',
            name='total_taken',
            field=models.IntegerField(default=0),
        ),
    ]
