# Generated by Django 2.1.3 on 2018-11-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20181117_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('slot', models.CharField(max_length=10)),
                ('ticks', models.IntegerField(default=20)),
            ],
        ),
    ]
